author: dobrakmato
database: false
main: me.dobrakmato.plugins.pexel.PexelCore.PexelCore
name: pexel-core
startup: postworld
version: 1.0

commands:
   arena:
     description: Pouziva sa na pracu s arenami.
     aliases: [minigamearena, marena]
     usage: /arena <mode> <name> <action> [param1] [param2]
   lobbyarena:
     description: Pouziva sa na pracu s lobbynami.
     usage: /lobbyarena <action> <name> [param1] [param2]   
   qj:
     description: Pouziva sa na quick-join.
     aliases: [quickjoin, join]
     usage: /qj [game]
   friend:
     description: Pouziva sa na pracu s priatelmi.
     aliases: [friends, f]
     usage: /friend <action> <playerName>
   party:
     description: Pouziva sa na pracu s priatelmi.
     aliases: [p]
     usage: /party <action> <playerName>
   settings:
     description: Pouziva sa na pracu s nastaveniami.
     aliases: [options, option, setting]
     usage: /settings <setting> <true/false>